[tools]
uv = "latest"
python = "latest"

[env.'_'.python.venv]
path = ".venv"
create = true
uv_create_args = ["--seed", "--quiet"]

[tasks.build_and_test]
depends = ["validate", "mypy"]

[tasks.validate]
run = "python _validate.py"
depends = ["pip-install"]

[tasks.mypy]
run = "mypy ."
depends = ["pip-install"]

[tasks.pip-install]
run = "pip install --requirement requirements.txt --quiet --disable-pip-version-check"
